Added client checker
swp-fu-eid/eid-fu-swp pull request #25
Opened 2017-08-10 19:01 UTC by BenjaminKeller

_**Disclaimer:**_ This branch contains part of the code of the branch check_for_eidclient having its original purpose.

This implements issue #3. The tests can be run using node:
```
cd static/test
npm install
jasmine
```
@Armagetron This should be integrated into travis, soon.

2017-08-11 13:10 UTC, nils-wisiol reviewed
Very nice work, in particular the tests for the client checker. I added some minor comments.

Please avoid whitespace changes, cf. #30, and squash some fixup commits, cf. comments in #23 

Approval delayed until #23 , #24 are settled

2017-08-11 13:10 UTC, nils-wisiol commented on static/html/js/clientChecker.js
> +							callback(clientUrls[index]);
why not `callback(url)`? :)

2017-08-11 13:10 UTC, nils-wisiol commented on static/test/package.json
> +  "description": "End-to-end tests for the EID project",
This PR contains changes that are also in #24. Please build PRs on top of each other instead.

2017-08-11 13:10 UTC, nils-wisiol commented on static/test/spec/clientChecker_spec.js
> +describe("The client checker", function() {
nice!

2017-08-11 13:10 UTC, nils-wisiol commented on static/html/js/clientChecker.js
> +				$.get(url.url + statusParam)
Name somewhat misleading. How about `that.eidClients` instead of `that.clientUrls` and `$.each(that.eidClients, function(index, eidClient))`?

2017-08-11 13:10 UTC, nils-wisiol commented on static/html/index.html
> +  </body>
Please squash this into the previous commit that changed this file.

2017-08-11 14:43 UTC, BenjaminKeller commented
I corrected everything.

2017-08-13 07:54 UTC, nils-wisiol requested changes
Please squash commits 5951b4e, 7d25c50, cf9de28, and 6de6cac into one to keep masters commit history clean.

2017-08-13 10:45 UTC, BenjaminKeller commented
Squashed commits. Thank you very much for your feedback. Is this a standard procedure to rewrite the history of branches?

2017-08-14 08:44 UTC, nils-wisiol commented
Yes it is; however GitHub only offers to either add all commits to master or to squash all commits into one and add it. I prefer to keep commits organized by their nature, hence I was asking to squash manually.

2017-08-14 08:44 UTC, merged