Add eid server types
swp-fu-eid/eid-fu-swp pull request #65
Opened 2017-09-01 12:23 UTC by larissazech

We implemented the eID Server Types.

Resolves: #51

2017-09-02 11:26 UTC, nielsgroth commented
Maybe we should consider to move the `eid_types` directory into `api/eid_server/`?

2017-09-04 12:02 UTC, nils-wisiol requested changes
Please consider the following points:

- use the unit test framework `assert` methods (`assertEqual`, `assertRaise`)
- limit lines to 120 chars (GitHub imposes this limit on reviews)
- organize commits by topic, don't include fix up in later commits

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/place.py
> +
two blank lines here (PEP8)

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/place.py
> +        valid_chars = all(i for i in map(lambda x: x in self.ICAO_ALPHABET, list(value)))
`i for i in` unnecessary here

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/place.py
> +
two blank lines (PEP8)

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/place.py
> +            raise TypeError("Country string has to consist of one or three characters, where each charachter is an ascii uppercase char or a whitespace.")
please break lines after 120 chars, as GitHub displays only 120 whenever I do reviews

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/type_check.py
> -    check(description, variable, int)
this (and related) fixups should be merged into previous commit

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/tests/version.py
> +        try:
use `assertRaise` here?

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/tests/attributeresponse.py
> +        assert r == self.VALID_RESPONSE_ALLOWED
use `assertEqual` here to have tests running even if some fail

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/operationsselector.py
> +    def __init__(self, documentType="PROHIBITED", issuingState="PROHIBITED", dateOfExpiry="PROHIBITED", givenNames="PROHIBITED", familyNames="PROHIBITED", artisticName="PROHIBITED", academicTitle="PR
break lines after 120 chars (GitHub has this limit for display of reviews)

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/eid_types/type_check.py
> +def check_bool(description, variable):
`check_bool` should have the same interface as `check_int` and `check_str`, i.e. first argument should be `variable_name` rather than `description`

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/tests/attributeselection.py
> +
PEP8: two blank lines

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/tests/attributeselection.py
> +        assert s == self.VALID_SELECTION_STRING_ALLOWED
use `assertEqual`

2017-09-04 12:02 UTC, nils-wisiol commented on api/boilerplate/tests/operationsselector.py
> +        operationsSelector = OperationsSelector(self.VALID_SELECTION_STRING_ALLOWED, self.VALID_SELECTION_STRING_ALLOWED, self.VALID_SELECTION_STRING_ALLOWED, self.VALID_SELECTION_STRING_ALLOWED, sel
break long lines after 120 chars

2017-09-04 17:08 UTC, larissazech commented on api/boilerplate/eid_types/place.py
> +
Done.

2017-09-05 13:44 UTC, m273d15 commented
Replaced by PR #70

2017-09-05 13:44 UTC, closed without merging