Add eid types for the eid server
swp-fu-eid/eid-fu-swp pull request #70
Opened 2017-09-05 13:43 UTC by m273d15

This PR replaces #65 .
* Replaced assert by assertEqual
* Replaced try catch by assertRaises
* Added blank lines as defined in PEP8
* Added newline if line is longer than 120 characters
* Sorted commits by types
* Moved all types and tests from the directory `boilerplate` to `eid_server`
Created by @m273d15 and @larissazech

2017-09-05 14:25 UTC, nils-wisiol requested changes
- Please fix indentation, in particular after line breaks
- please use python regex rather than run time-compiled expressions

2017-09-05 14:25 UTC, nils-wisiol commented on run_ci.sh
> +exit 0
indentation

2017-09-05 14:25 UTC, nils-wisiol commented on api/boilerplate/eid_types/sessionid.py
> +        i = 16
What does this do? Maybe add some docs.

2017-09-05 14:25 UTC, nils-wisiol commented on api/boilerplate/eid_types/sessionid.py
> +            + list(range(ord('a'), ord('f') + 1))):
indentation

2017-09-05 14:25 UTC, nils-wisiol commented on api/boilerplate/eid_types/hexbinary.py
> +        pattern = "^([A-F,a-f,0-9]{2})*$"
please use python built-in regex

2017-09-05 14:25 UTC, nils-wisiol commented on api/boilerplate/eid_types/hexbinary.py
> +        value, pattern)
indentation

2017-09-07 15:22 UTC, larissazech commented
@nils-wisiol, @m273d15 and I fixed the indentation and the regex and rebased to master. Can we merge?

2017-09-07 15:49 UTC, nils-wisiol reviewed
- generation of session ids needs refactoring
- [avoid `import *`](https://stackoverflow.com/a/2386740) (the test's `__init__` file is an exception here)
- scipy appears to be not needed, don't install it

2017-09-07 15:49 UTC, nils-wisiol commented on api/eid_server/eid_types/sessionid.py
> +import numpy as np
unused import

2017-09-07 15:49 UTC, nils-wisiol commented on api/eid_server/eid_types/sessionid.py
> +    def id(self):
please add some docs here

2017-09-07 15:49 UTC, nils-wisiol commented on api/eid_server/eid_types/sessionid.py
> +            a = random.bytes(i)
numpy.random is not a cryptographically safe way to generate random numbers

2017-09-07 15:49 UTC, nils-wisiol commented on api/eid_server/eid_types/sessionid.py
> +            a = random.bytes(i)
why don't you just generate 16 bytes of random data?

Also, you could use [random.choice](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.choice.html#numpy.random.choice)? (After seeding it with crypto-safe random numbers.)

2017-09-07 17:20 UTC, larissazech commented
Taken from the eID Server specification:

> The type SessionType SHALL be used to uniquely identify a request to the eID-Interface. The eID-Server MUST generate values for the ID element to identify different requests for Online-Authentication. The value of the element ID MUST be random and at least 32 characters long in hexadecimal representation so that it's not easy to guess. The software component generating the random numbers used as IDs SHALL fulfill the requirements described in [TR-03116-4] Section 6.2: Zufallszahlen and the eID-Service MUST ensure that no active sessions using identical IDs exist in the same context.The eService SHALL only use valid session IDs for calls of the function getResult.

I would suggest to leave the generation of a random number to the component instantiating a SessionType and to only check for the 16Bits HexBinary (as described in the xsd) here. 

@m273d15 @Armagetron Agreed?

2017-09-07 18:35 UTC, larissazech commented on api/eid_server/eid_types/sessionid.py
> +        check("id", value, HexBinary16)
I refactored as suggested. For being able to rewind the changes, I pushed a whole new commit. If the changes are approved, I will squash it to Commit 702a6c493437e41deb6a27b1cde03bf53c6f47c4 .

2017-09-07 21:00 UTC, larissazech commented
We discussed the SessionID-issue internally and agreed upon the suggested solution. Commit history has been cleaned. Can we merge?

2017-09-07 21:09 UTC, nils-wisiol requested changes
The specification you quoted yourself explicitly states

> The eID-Server MUST generate values for the ID element

So, unless the other component is also part of the eId server, I'd say this needs to be done here.

Unfortunately, [this is not ready to merge](https://github.com/swp-fu-eid/eid-fu-swp/pull/70#pullrequestreview-61264027).

2017-09-07 21:09 UTC, nils-wisiol commented on api/eid_server/tests/personaldata.py
> +    "Berlin, DE", "no place info")
indentation

2017-09-09 13:22 UTC, nils-wisiol approved these changes

2017-09-09 13:22 UTC, nils-wisiol commented
Let's merge this once we need it

2017-09-25 10:16 UTC, merged